nodeLinker: node-modules

npmPreapprovedPackages:
  - "@vempain/*"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: "${VEMPAIN_ACTION_TOKEN-}"

npmScopes:
  vempain:
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
