name: CI

permissions:
  contents: write
  packages: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    uses: Vempain/vempain-workflows/.github/workflows/frontend-spa.yaml@main
    with:
      use_scoped_registry: true
      use_immutable_install: true
    secrets:
      VEMPAIN_ACTION_TOKEN: ${{ secrets.VEMPAIN_ACTION_TOKEN || github.token }}
